// GENERATED by _dev/build_bpdocs.js — do not hand-edit.
//
// Season 1 "KORD BREACH" BattlePass documents: TerraGroup documentation found
// in raid and turned in for BattlePass rewards. Each type is tied to a few
// maps. They behave like task items — everyone can pick one up, PMC or Scav,
// in every game mode.
//
// ⚠️ DESCRIPTIONS, NOT COORDINATES. No source has positions for these:
// json.tarkov.dev has no item record at all (just the name in its locale file,
// no category, no properties, no lootLoose entry anywhere), and the wiki gives
// prose and screenshots. The app therefore LISTS these in the map side panel,
// as it already does for story objectives, and shows a real pin only where one
// has been hand-placed through the dev map editor.
//
// Source: escapefromtarkov.fandom.com, read 2026-08-17.
// Community-maintained and only as current as its editors; re-run to refresh.

const BP_DOCS = [
 {
  "id": "6a31824878450ec91c0ea1ae",
  "name": "Blueprints and technical documentation",
  "spots": {
   "Factory": [],
   "Interchange": [],
   "The Labyrinth": []
  },
  "pins": {
   "Factory": [
    {
     "x": 25.8,
     "z": -26.08,
     "floor": 0,
     "spot": null
    },
    {
     "x": 33.91,
     "z": -36.08,
     "floor": -1,
     "spot": null
    },
    {
     "x": -15.4,
     "z": -25.86,
     "floor": -1,
     "spot": null
    },
    {
     "x": 20.29,
     "z": 42.22,
     "floor": 1,
     "spot": null
    },
    {
     "x": 26.66,
     "z": 43.04,
     "floor": -1,
     "spot": null
    },
    {
     "x": 28.8,
     "z": 37.97,
     "floor": 1,
     "spot": null
    },
    {
     "x": 11.58,
     "z": 38.85,
     "floor": 1,
     "spot": null
    },
    {
     "x": 19.07,
     "z": -22.27,
     "floor": 2,
     "spot": null
    },
    {
     "x": 12.91,
     "z": 39.71,
     "floor": -1,
     "spot": null
    },
    {
     "x": 27.19,
     "z": 36.11,
     "floor": 1,
     "spot": null
    },
    {
     "x": 25.65,
     "z": -35.18,
     "floor": -1,
     "spot": null
    },
    {
     "x": 27.84,
     "z": -35.76,
     "floor": 0,
     "spot": null
    }
   ],
   "Interchange": [
    {
     "x": -68.17,
     "z": -157.55,
     "floor": 0,
     "spot": null
    },
    {
     "x": 3.33,
     "z": -232.75,
     "floor": 0,
     "spot": null
    },
    {
     "x": -67.84,
     "z": 54.12,
     "floor": 0,
     "spot": null
    },
    {
     "x": -92.75,
     "z": 106.8,
     "floor": 0,
     "spot": null
    },
    {
     "x": 35.6,
     "z": 149.21,
     "floor": 0,
     "spot": null
    },
    {
     "x": -79.64,
     "z": -146.27,
     "floor": 0,
     "spot": null
    },
    {
     "x": 60.67,
     "z": -25.48,
     "floor": 0,
     "spot": null
    },
    {
     "x": -64.52,
     "z": -99.52,
     "floor": 0,
     "spot": null
    },
    {
     "x": 2.06,
     "z": -290.43,
     "floor": 0,
     "spot": null
    },
    {
     "x": 85.21,
     "z": 100.42,
     "floor": 0,
     "spot": null
    },
    {
     "x": -79.11,
     "z": 43.99,
     "floor": 0,
     "spot": null
    },
    {
     "x": -84.55,
     "z": 113.35,
     "floor": 0,
     "spot": null
    },
    {
     "x": 95.84,
     "z": -84.09,
     "floor": 0,
     "spot": null
    }
   ],
   "The Labyrinth": [
    {
     "x": -16.38,
     "z": 8.72,
     "floor": -1,
     "spot": null
    },
    {
     "x": 9.73,
     "z": 2.48,
     "floor": -1,
     "spot": null
    },
    {
     "x": -14.63,
     "z": 51.89,
     "floor": -1,
     "spot": null
    },
    {
     "x": -11.07,
     "z": 26.68,
     "floor": -1,
     "spot": null
    },
    {
     "x": -7.23,
     "z": 35.96,
     "floor": -1,
     "spot": null
    },
    {
     "x": -8.41,
     "z": 22.97,
     "floor": -1,
     "spot": null
    },
    {
     "x": 17.08,
     "z": 7.88,
     "floor": -1,
     "spot": null
    },
    {
     "x": 12.7,
     "z": 4.51,
     "floor": -1,
     "spot": null
    },
    {
     "x": 3.61,
     "z": 28.84,
     "floor": -1,
     "spot": null
    },
    {
     "x": 8.44,
     "z": -11.01,
     "floor": -1,
     "spot": null
    },
    {
     "x": 1.15,
     "z": 54.36,
     "floor": -1,
     "spot": null
    },
    {
     "x": 12.23,
     "z": 31.39,
     "floor": -1,
     "spot": null
    },
    {
     "x": -27.2,
     "z": 35.88,
     "floor": -1,
     "spot": null
    },
    {
     "x": 19.22,
     "z": 4.61,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a3183258f113efdb7093622",
  "name": "Classified documents",
  "spots": {}
 },
 {
  "id": "6a31807f17005505b70d5827",
  "name": "Financial documents",
  "spots": {
   "Customs": [],
   "Interchange": [],
   "Streets of Tarkov": []
  },
  "pins": {
   "Customs": [
    {
     "x": 77.97,
     "z": -162.1,
     "floor": 1,
     "spot": null
    },
    {
     "x": 77.65,
     "z": -155.94,
     "floor": 1,
     "spot": null
    },
    {
     "x": 318.24,
     "z": -186.86,
     "floor": -1,
     "spot": null
    },
    {
     "x": -207.19,
     "z": -54.46,
     "floor": -1,
     "spot": null
    },
    {
     "x": 93.68,
     "z": -59.59,
     "floor": -1,
     "spot": null
    },
    {
     "x": -200.72,
     "z": -98.71,
     "floor": 1,
     "spot": null
    },
    {
     "x": 169.6,
     "z": 156.81,
     "floor": 2,
     "spot": null
    },
    {
     "x": 172.86,
     "z": 185.88,
     "floor": 1,
     "spot": null
    },
    {
     "x": 225.09,
     "z": 141.38,
     "floor": -1,
     "spot": null
    },
    {
     "x": 263.12,
     "z": -75.93,
     "floor": 2,
     "spot": null
    }
   ],
   "Interchange": [
    {
     "x": -78.45,
     "z": -148.97,
     "floor": 0,
     "spot": null
    },
    {
     "x": 4.03,
     "z": -297.99,
     "floor": 0,
     "spot": null
    },
    {
     "x": 420.91,
     "z": 176.8,
     "floor": -1,
     "spot": null
    },
    {
     "x": 86.34,
     "z": 104.33,
     "floor": 0,
     "spot": null
    },
    {
     "x": -206.98,
     "z": -356.84,
     "floor": -1,
     "spot": null
    },
    {
     "x": 41.34,
     "z": -223.7,
     "floor": 0,
     "spot": null
    },
    {
     "x": 15.96,
     "z": -134.3,
     "floor": 1,
     "spot": null
    },
    {
     "x": -12.46,
     "z": -96.33,
     "floor": 1,
     "spot": null
    },
    {
     "x": -200.3,
     "z": -353.79,
     "floor": -1,
     "spot": null
    },
    {
     "x": 130.63,
     "z": 267.12,
     "floor": -1,
     "spot": null
    },
    {
     "x": 21.78,
     "z": -133.15,
     "floor": 0,
     "spot": null
    },
    {
     "x": -65.71,
     "z": 54.11,
     "floor": 0,
     "spot": null
    },
    {
     "x": -67.08,
     "z": 41.75,
     "floor": 0,
     "spot": null
    },
    {
     "x": -61.22,
     "z": -47.48,
     "floor": 0,
     "spot": null
    },
    {
     "x": 79.46,
     "z": -208.41,
     "floor": 0,
     "spot": null
    },
    {
     "x": -64.97,
     "z": -158.68,
     "floor": 0,
     "spot": null
    }
   ],
   "Streets of Tarkov": [
    {
     "x": 72.61,
     "z": -20.63,
     "floor": -1,
     "spot": null
    },
    {
     "x": 59.92,
     "z": -60.86,
     "floor": -1,
     "spot": null
    },
    {
     "x": 57.11,
     "z": -70.91,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a3182dc6cd8de21cf0a3a7d",
  "name": "Medical documents",
  "spots": {
   "Ground Zero": [],
   "The Lab": [],
   "The Labyrinth": []
  },
  "pins": {
   "Ground Zero": [
    {
     "x": -5.5,
     "z": 61.98,
     "floor": 1,
     "spot": null
    },
    {
     "x": 23.25,
     "z": 71.97,
     "floor": -1,
     "spot": null
    },
    {
     "x": -18.25,
     "z": 44.85,
     "floor": 1,
     "spot": null
    },
    {
     "x": -6.34,
     "z": 72.46,
     "floor": 1,
     "spot": null
    },
    {
     "x": 49.36,
     "z": 252.41,
     "floor": -1,
     "spot": null
    },
    {
     "x": 101.48,
     "z": 112.59,
     "floor": 1,
     "spot": null
    },
    {
     "x": 146.99,
     "z": 237.58,
     "floor": -1,
     "spot": null
    },
    {
     "x": 101.83,
     "z": 154.1,
     "floor": -1,
     "spot": null
    },
    {
     "x": 81.68,
     "z": 129.62,
     "floor": -1,
     "spot": null
    }
   ],
   "The Lab": [
    {
     "x": -129.04,
     "z": -392.5,
     "floor": -1,
     "spot": null
    },
    {
     "x": -108.22,
     "z": -443.93,
     "floor": -1,
     "spot": null
    },
    {
     "x": -122.05,
     "z": -368.49,
     "floor": 0,
     "spot": null
    },
    {
     "x": -231.6,
     "z": -342.87,
     "floor": -1,
     "spot": null
    },
    {
     "x": -114.1,
     "z": -364.32,
     "floor": 0,
     "spot": null
    },
    {
     "x": -134.35,
     "z": -408.18,
     "floor": 0,
     "spot": null
    },
    {
     "x": -86.64,
     "z": -432.28,
     "floor": -1,
     "spot": null
    },
    {
     "x": -126.15,
     "z": -352.15,
     "floor": -1,
     "spot": null
    },
    {
     "x": -121.9,
     "z": -360.84,
     "floor": 0,
     "spot": null
    },
    {
     "x": -233.62,
     "z": -312.18,
     "floor": 0,
     "spot": null
    }
   ],
   "The Labyrinth": [
    {
     "x": 12.95,
     "z": 9.43,
     "floor": -1,
     "spot": null
    },
    {
     "x": -0.28,
     "z": 55.06,
     "floor": -1,
     "spot": null
    },
    {
     "x": -17.15,
     "z": 35.21,
     "floor": -1,
     "spot": null
    },
    {
     "x": -7.4,
     "z": 30.78,
     "floor": -1,
     "spot": null
    },
    {
     "x": 7.41,
     "z": -10.78,
     "floor": -1,
     "spot": null
    },
    {
     "x": 12.2,
     "z": 33.69,
     "floor": -1,
     "spot": null
    },
    {
     "x": 14.8,
     "z": 16.63,
     "floor": -1,
     "spot": null
    },
    {
     "x": -5.39,
     "z": 10.15,
     "floor": -1,
     "spot": null
    },
    {
     "x": 12.31,
     "z": 18.79,
     "floor": -1,
     "spot": null
    },
    {
     "x": -9.32,
     "z": 30.44,
     "floor": -1,
     "spot": null
    },
    {
     "x": -6.11,
     "z": 28.17,
     "floor": -1,
     "spot": null
    },
    {
     "x": -0.9,
     "z": 35.83,
     "floor": -1,
     "spot": null
    },
    {
     "x": 8.95,
     "z": 5.21,
     "floor": -1,
     "spot": null
    },
    {
     "x": -25.1,
     "z": 40.4,
     "floor": -1,
     "spot": null
    },
    {
     "x": -26.62,
     "z": 9.17,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a317b9692cfdcddcb02a58e",
  "name": "PMC personnel files",
  "spots": {
   "Icebreaker": [],
   "Lighthouse": [],
   "Reserve": []
  },
  "pins": {
   "Lighthouse": [
    {
     "x": -63.28,
     "z": -734.4,
     "floor": -1,
     "spot": null
    },
    {
     "x": -186.66,
     "z": -210.03,
     "floor": -1,
     "spot": null
    },
    {
     "x": -92.48,
     "z": -490.18,
     "floor": -1,
     "spot": null
    },
    {
     "x": -88.21,
     "z": -72.28,
     "floor": -1,
     "spot": null
    },
    {
     "x": -106.57,
     "z": -12.92,
     "floor": -1,
     "spot": null
    },
    {
     "x": -120.65,
     "z": 86.1,
     "floor": -1,
     "spot": null
    }
   ],
   "Reserve": [
    {
     "x": -127.97,
     "z": -21.83,
     "floor": 0,
     "spot": null
    },
    {
     "x": -42.25,
     "z": 133.2,
     "floor": 0,
     "spot": null
    },
    {
     "x": -4.38,
     "z": 175.43,
     "floor": -1,
     "spot": null
    },
    {
     "x": -42.14,
     "z": 174.18,
     "floor": -1,
     "spot": null
    },
    {
     "x": -11.03,
     "z": 196.9,
     "floor": -1,
     "spot": null
    },
    {
     "x": -16.12,
     "z": 175.6,
     "floor": -1,
     "spot": null
    },
    {
     "x": -159.49,
     "z": 0.03,
     "floor": -1,
     "spot": null
    },
    {
     "x": 59.77,
     "z": 103.12,
     "floor": -1,
     "spot": null
    },
    {
     "x": 82.04,
     "z": -14.23,
     "floor": -1,
     "spot": null
    },
    {
     "x": 27.54,
     "z": -93.2,
     "floor": -1,
     "spot": null
    },
    {
     "x": 22.47,
     "z": -24.32,
     "floor": -1,
     "spot": null
    },
    {
     "x": 60.29,
     "z": -114.4,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a3181f178450ec91c0ea1aa",
  "name": "Project documentation",
  "spots": {
   "Customs": [],
   "Factory": [],
   "Reserve": []
  },
  "pins": {
   "Customs": [
    {
     "x": 78.92,
     "z": -158.42,
     "floor": 1,
     "spot": null
    },
    {
     "x": 78.49,
     "z": -166.72,
     "floor": 1,
     "spot": null
    },
    {
     "x": 315.76,
     "z": -180.25,
     "floor": -1,
     "spot": null
    },
    {
     "x": 197.28,
     "z": -102.77,
     "floor": -1,
     "spot": null
    },
    {
     "x": 68.9,
     "z": -169.76,
     "floor": -1,
     "spot": null
    },
    {
     "x": 25.41,
     "z": -58.95,
     "floor": 1,
     "spot": null
    },
    {
     "x": 90.25,
     "z": -58.36,
     "floor": 2,
     "spot": null
    },
    {
     "x": 173.68,
     "z": 185.67,
     "floor": 1,
     "spot": null
    },
    {
     "x": 106.01,
     "z": -87.31,
     "floor": -1,
     "spot": null
    }
   ],
   "Factory": [
    {
     "x": 27.93,
     "z": 41.88,
     "floor": 1,
     "spot": null
    },
    {
     "x": 11.42,
     "z": 41.67,
     "floor": 1,
     "spot": null
    },
    {
     "x": 55.45,
     "z": 24.14,
     "floor": -1,
     "spot": null
    },
    {
     "x": 26.77,
     "z": 42.55,
     "floor": -1,
     "spot": null
    },
    {
     "x": 30.34,
     "z": -34.69,
     "floor": -1,
     "spot": null
    },
    {
     "x": 41.48,
     "z": -15.36,
     "floor": -1,
     "spot": null
    },
    {
     "x": 23.01,
     "z": 39.67,
     "floor": 1,
     "spot": null
    },
    {
     "x": -22.78,
     "z": 29.32,
     "floor": 0,
     "spot": null
    },
    {
     "x": 12.67,
     "z": 43.05,
     "floor": -1,
     "spot": null
    },
    {
     "x": 26.34,
     "z": -18.96,
     "floor": 0,
     "spot": null
    }
   ],
   "Reserve": [
    {
     "x": -115.92,
     "z": 33.37,
     "floor": 0,
     "spot": null
    },
    {
     "x": -108.07,
     "z": 17.8,
     "floor": 0,
     "spot": null
    },
    {
     "x": -5.11,
     "z": 175.42,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a31830dde69ceafd805afa0",
  "name": "Technical documentation",
  "spots": {
   "Lighthouse": [],
   "Shoreline": [],
   "Woods": []
  },
  "pins": {
   "Lighthouse": [
    {
     "x": -95.73,
     "z": -489.91,
     "floor": -1,
     "spot": null
    },
    {
     "x": -174.87,
     "z": -645.22,
     "floor": -1,
     "spot": null
    },
    {
     "x": -191.49,
     "z": -196.75,
     "floor": -1,
     "spot": null
    },
    {
     "x": 134.16,
     "z": -186.62,
     "floor": -1,
     "spot": null
    },
    {
     "x": 140.49,
     "z": -129.05,
     "floor": -1,
     "spot": null
    },
    {
     "x": -78.18,
     "z": -85.73,
     "floor": -1,
     "spot": null
    },
    {
     "x": -59.9,
     "z": -129.28,
     "floor": -1,
     "spot": null
    },
    {
     "x": 29.32,
     "z": -620.64,
     "floor": -1,
     "spot": null
    },
    {
     "x": -116.87,
     "z": 97.17,
     "floor": -1,
     "spot": null
    },
    {
     "x": -86.94,
     "z": -66.16,
     "floor": -1,
     "spot": null
    },
    {
     "x": -68.24,
     "z": 112.7,
     "floor": -1,
     "spot": null
    }
   ],
   "Shoreline": [
    {
     "x": -319.05,
     "z": 485.49,
     "floor": -1,
     "spot": null
    },
    {
     "x": -180.99,
     "z": -75.35,
     "floor": 2,
     "spot": null
    },
    {
     "x": -241.37,
     "z": 204,
     "floor": -1,
     "spot": null
    },
    {
     "x": -627.65,
     "z": -231.7,
     "floor": -1,
     "spot": null
    },
    {
     "x": 93.95,
     "z": 117.39,
     "floor": -1,
     "spot": null
    }
   ],
   "Woods": [
    {
     "x": -248.69,
     "z": -22.3,
     "floor": -1,
     "spot": null
    },
    {
     "x": 295.38,
     "z": -507.65,
     "floor": -1,
     "spot": null
    },
    {
     "x": 226.51,
     "z": -712.59,
     "floor": -1,
     "spot": null
    },
    {
     "x": -43.15,
     "z": -251.39,
     "floor": -1,
     "spot": null
    },
    {
     "x": 141,
     "z": -725.68,
     "floor": -1,
     "spot": null
    },
    {
     "x": -276.57,
     "z": -422.52,
     "floor": -1,
     "spot": null
    },
    {
     "x": -2.19,
     "z": -75.08,
     "floor": -1,
     "spot": null
    },
    {
     "x": -475.71,
     "z": -178.76,
     "floor": -1,
     "spot": null
    },
    {
     "x": 370.15,
     "z": 123.54,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a31828557705071410ca00e",
  "name": "Test documentation",
  "spots": {
   "Icebreaker": [],
   "Shoreline": [],
   "Woods": []
  },
  "pins": {
   "Shoreline": [
    {
     "x": -317.95,
     "z": 497.52,
     "floor": -1,
     "spot": null
    },
    {
     "x": -614.52,
     "z": -180.87,
     "floor": -1,
     "spot": null
    },
    {
     "x": -511.58,
     "z": 237.69,
     "floor": -1,
     "spot": null
    },
    {
     "x": -349.01,
     "z": -89.68,
     "floor": 2,
     "spot": null
    }
   ],
   "Woods": [
    {
     "x": -544.33,
     "z": -200.85,
     "floor": -1,
     "spot": null
    },
    {
     "x": -455.92,
     "z": -366.3,
     "floor": -1,
     "spot": null
    },
    {
     "x": 239.01,
     "z": -70.45,
     "floor": -1,
     "spot": null
    },
    {
     "x": -513.47,
     "z": -394.72,
     "floor": -1,
     "spot": null
    },
    {
     "x": 309.77,
     "z": -460.9,
     "floor": -1,
     "spot": null
    },
    {
     "x": 272.98,
     "z": -510.36,
     "floor": -1,
     "spot": null
    },
    {
     "x": -513.4,
     "z": -177.57,
     "floor": -1,
     "spot": null
    },
    {
     "x": 285.15,
     "z": -517.1,
     "floor": -1,
     "spot": null
    },
    {
     "x": 272.54,
     "z": -439.2,
     "floor": -1,
     "spot": null
    },
    {
     "x": -200.66,
     "z": 230.49,
     "floor": -1,
     "spot": null
    }
   ]
  }
 },
 {
  "id": "6a3182b72fd891345e047eef",
  "name": "User documentation",
  "spots": {
   "Ground Zero": [],
   "Streets of Tarkov": [],
   "The Lab": []
  },
  "pins": {
   "Ground Zero": [
    {
     "x": 61.06,
     "z": 150.22,
     "floor": 1,
     "spot": 2
    },
    {
     "x": -36.45,
     "z": 65.01,
     "floor": 1,
     "spot": 5
    },
    {
     "x": -10.78,
     "z": 40.85,
     "floor": 1,
     "spot": 6
    },
    {
     "x": -44.74,
     "z": 64.44,
     "floor": 1,
     "spot": 7
    },
    {
     "x": 14.18,
     "z": 66.05,
     "floor": -1,
     "spot": 8
    },
    {
     "x": 52.65,
     "z": 137.1,
     "floor": -1,
     "spot": 3
    },
    {
     "x": -6.85,
     "z": 56.26,
     "floor": 1,
     "spot": 0
    },
    {
     "x": -27.63,
     "z": 80.47,
     "floor": 1,
     "spot": 1
    },
    {
     "x": -22.95,
     "z": 83.67,
     "floor": 1,
     "spot": 4
    },
    {
     "x": 55.02,
     "z": 152.84,
     "floor": -1,
     "spot": null
    }
   ],
   "Streets of Tarkov": [
    {
     "x": 59.54,
     "z": -70.89,
     "floor": -1,
     "spot": 1
    },
    {
     "x": 67.51,
     "z": -58.46,
     "floor": -1,
     "spot": 2
    },
    {
     "x": -170.37,
     "z": 224.9,
     "floor": 1,
     "spot": 3
    },
    {
     "x": 84.02,
     "z": -23.48,
     "floor": -1,
     "spot": 4
    },
    {
     "x": 115.57,
     "z": -40.56,
     "floor": 1,
     "spot": null
    },
    {
     "x": 171.43,
     "z": 162.56,
     "floor": -1,
     "spot": null
    },
    {
     "x": -24.51,
     "z": -32.79,
     "floor": 1,
     "spot": null
    },
    {
     "x": 135.09,
     "z": 5.32,
     "floor": -1,
     "spot": null
    },
    {
     "x": 139.8,
     "z": 378.4,
     "floor": 1,
     "spot": null
    },
    {
     "x": 152.25,
     "z": 345.24,
     "floor": -1,
     "spot": null
    },
    {
     "x": 49,
     "z": 34.42,
     "floor": -1,
     "spot": null
    },
    {
     "x": -67.75,
     "z": 49.89,
     "floor": 1,
     "spot": null
    },
    {
     "x": -53.16,
     "z": 62.13,
     "floor": -1,
     "spot": null
    }
   ],
   "The Lab": [
    {
     "x": -268.62,
     "z": -325.83,
     "floor": 0,
     "spot": 2
    },
    {
     "x": -231.87,
     "z": -345.41,
     "floor": 0,
     "spot": 3
    },
    {
     "x": -161.18,
     "z": -347.31,
     "floor": 0,
     "spot": 4
    },
    {
     "x": -172.73,
     "z": -342.41,
     "floor": 0,
     "spot": null
    },
    {
     "x": -118.83,
     "z": -445.38,
     "floor": -1,
     "spot": null
    },
    {
     "x": -244.06,
     "z": -382.48,
     "floor": 0,
     "spot": null
    },
    {
     "x": -225.81,
     "z": -308.43,
     "floor": 0,
     "spot": null
    },
    {
     "x": -263.64,
     "z": -342.79,
     "floor": -1,
     "spot": null
    },
    {
     "x": -243.83,
     "z": -382.5,
     "floor": 0,
     "spot": null
    },
    {
     "x": -187.66,
     "z": -407.33,
     "floor": 0,
     "spot": null
    },
    {
     "x": -148.4,
     "z": -393.4,
     "floor": 0,
     "spot": null
    },
    {
     "x": -251.16,
     "z": -368.43,
     "floor": 0,
     "spot": null
    }
   ]
  }
 }
];

if (typeof module !== 'undefined') module.exports = { BP_DOCS };
