// GENERATED by _dev/build_bpdocs.js — do not hand-edit.
//
// Season 1 "KORD BREACH" BattlePass documents: TerraGroup documentation found
// in raid and turned in for BattlePass rewards. Each type is tied to a few
// maps. They behave like task items — everyone can pick one up, PMC or Scav,
// in every game mode.
//
// ⚠️ DESCRIPTIONS, NOT COORDINATES. No source has positions for these:
// json.tarkov.dev has no item record at all (just the name in its locale file,
// no category, no properties, no lootLoose entry anywhere), and the wiki gives
// prose and screenshots. The app therefore LISTS these in the map side panel,
// as it already does for story objectives, and shows a real pin only where one
// has been hand-placed through the dev map editor.
//
// Source: escapefromtarkov.fandom.com, read 2026-08-06.
// Community-maintained and only as current as its editors; re-run to refresh.

const BP_DOCS = [
 {
  "id": "6a31824878450ec91c0ea1ae",
  "name": "Blueprints and technical documentation",
  "spots": {
   "Factory": [],
   "Interchange": [],
   "The Labyrinth": []
  }
 },
 {
  "id": "6a3183258f113efdb7093622",
  "name": "Classified documents",
  "spots": {}
 },
 {
  "id": "6a31807f17005505b70d5827",
  "name": "Financial documents",
  "spots": {
   "Customs": [],
   "Interchange": [],
   "Streets of Tarkov": []
  }
 },
 {
  "id": "6a3182dc6cd8de21cf0a3a7d",
  "name": "Medical documents",
  "spots": {
   "Ground Zero": [],
   "The Lab": [],
   "The Labyrinth": []
  }
 },
 {
  "id": "6a317b9692cfdcddcb02a58e",
  "name": "PMC personnel files",
  "spots": {
   "Icebreaker": [],
   "Lighthouse": [],
   "Reserve": []
  }
 },
 {
  "id": "6a3181f178450ec91c0ea1aa",
  "name": "Project documentation",
  "spots": {
   "Customs": [],
   "Factory": [],
   "Reserve": []
  }
 },
 {
  "id": "6a31830dde69ceafd805afa0",
  "name": "Technical documentation",
  "spots": {
   "Lighthouse": [],
   "Shoreline": [],
   "Woods": []
  }
 },
 {
  "id": "6a31828557705071410ca00e",
  "name": "Test documentation",
  "spots": {
   "Icebreaker": [],
   "Shoreline": [],
   "Woods": []
  }
 },
 {
  "id": "6a3182b72fd891345e047eef",
  "name": "User documentation",
  "spots": {
   "Ground Zero": [],
   "Streets of Tarkov": [],
   "The Lab": []
  },
  "pins": {
   "Ground Zero": [
    {
     "x": 61.06,
     "z": 150.22,
     "floor": 1,
     "spot": 2
    },
    {
     "x": -36.45,
     "z": 65.01,
     "floor": 1,
     "spot": 5
    },
    {
     "x": -10.78,
     "z": 40.85,
     "floor": 1,
     "spot": 6
    },
    {
     "x": -44.74,
     "z": 64.44,
     "floor": 1,
     "spot": 7
    },
    {
     "x": 14.18,
     "z": 66.05,
     "floor": -1,
     "spot": 8
    },
    {
     "x": 52.65,
     "z": 137.1,
     "floor": -1,
     "spot": 3
    },
    {
     "x": -6.85,
     "z": 56.26,
     "floor": 1,
     "spot": 0
    },
    {
     "x": -27.63,
     "z": 80.47,
     "floor": 1,
     "spot": 1
    },
    {
     "x": -22.95,
     "z": 83.67,
     "floor": 1,
     "spot": 4
    }
   ],
   "Streets of Tarkov": [
    {
     "x": 62.41,
     "z": -76.33,
     "floor": -1,
     "spot": 1
    },
    {
     "x": 67.51,
     "z": -58.46,
     "floor": -1,
     "spot": 2
    },
    {
     "x": -172.38,
     "z": 224.9,
     "floor": 1,
     "spot": 3
    },
    {
     "x": 85.64,
     "z": -24.65,
     "floor": -1,
     "spot": 4
    }
   ],
   "The Lab": [
    {
     "x": -267.39,
     "z": -318.61,
     "floor": 0,
     "spot": 2
    },
    {
     "x": -232.62,
     "z": -342.91,
     "floor": 0,
     "spot": 3
    },
    {
     "x": -161.18,
     "z": -347.31,
     "floor": 0,
     "spot": 4
    }
   ]
  }
 }
];

if (typeof module !== 'undefined') module.exports = { BP_DOCS };
