// GENERATED by _dev/build_wikinames.js — do not hand-edit.
//
// Quest names and quest-givers that patch 1.1.0 changed and tarkov.dev has not.
// Sourced from the wiki's own page moves: a renamed quest leaves a #REDIRECT
// behind at its old title, which is a structural fact rather than prose.
//
// Keyed by task ID, which never changes — so this is a display layer only and
// can never affect recorded progress.
//
// Source: escapefromtarkov.fandom.com, read 2026-08-05.
// Community-maintained and only as current as its editors; re-run to refresh.

const WIKI_NAMES = {
 "5ac23c6186f7741247042bad": "Gunsmith - MP-133",
 "5d25e44386f77409453bce7b": "The Huntsman Path - Angry Watchman",
 "59689ee586f7740d1570bbd5": "Sanitary Standards",
 "5ac2426c86f774138762edfe": "Gunsmith - AKS-74U",
 "59c124d686f774189b3c843f": "Oil Run",
 "59689fbd86f7740d137ebfc4": "Operation Aquarius",
 "5968eb3186f7741dde183a4d": "Blood in the Water",
 "5ac2428686f77412450b42bf": "Gunsmith - HK MP5",
 "5969f90786f77420d2328015": "Charity",
 "5a27c99a86f7747d2c6bdd8e": "Friend From the West",
 "639872f9decada40426d3447": "Gunsmith - OP-SKS",
 "5ede55112c95834b583f052a": "The Bunker",
 "5ae3267986f7742a413592fe": "Gunsmith - Model 870",
 "59c9392986f7742f6923add2": "Aid Stations",
 "59ca1a6286f774509a270942": "Ironclad Proof",
 "5ac345dc86f774288030817f": "Playing the Market",
 "5ac3467986f7741d6224abc2": "Ill-Wisher",
 "5a03153686f77442d90e2171": "One-Way Ticket",
 "5a27b9de86f77464e5044585": "The Cult",
 "5a0327ba86f77456b9154236": "Fuel Shortage",
 "5a03296886f774569778596a": "I Need More Power",
 "5a0449d586f77474e66227b7": "Master Key",
 "5a27bafb86f7741c73584017": "Chemical Experiments",
 "5a27bb1e86f7741f27621b7e": "Cargo X",
 "5a27bb3d86f77411ea361a21": "Tracker",
 "5ac346a886f7744e1b083d67": "Rat Hunting",
 "61958c366726521dd96828ec": "Gifts from Tarkov",
 "64f731ab83cfca080a361e42": "Pets Won't Need It",
 "5ae3270f86f77445ba41d4dd": "Gunsmith - AKM",
 "5ac3462b86f7741d6118b983": "Farming",
 "5ac3464c86f7741d651d6877": "Semiconductor Crisis",
 "5c0bde0986f77479cf22c2f8": "Shooter Born in Heaven",
 "5ac244eb86f7741356335af1": "Gunsmith - M4A1",
 "5ae4493d86f7744b8e15aa8f": "A Big Loss",
 "608974af4b05530f55550c21": "Reserve Expert",
 "5ae448f286f77448d73c0131": "Fuel Crisis",
 "5ae4493486f7744efa289417": "Inventory Files",
 "5ae3277186f7745973054106": "Gunsmith - AKS-74N",
 "676529af9c90953d090882e7": "Gunsmith Master - Part 12",
 "66aa58245ab22944110db6e9": "New Paths",
 "64f3176921045e77405d63b5": "Paramedic",
 "5c0bd94186f7747a727f09b2": "The Tarkov Import",
 "5a27ba1c86f77461ea5a3c56": "Weapons Circulation",
 "6179ac7511973d018217d0b9": "Easy Job",
 "639872fa9b4fb827b200d8e5": "Gunsmith - P226R",
 "5ae327c886f7745c7b3f2f3f": "Gunsmith - AK-105",
 "5d25e44f86f77443e625e385": "The Huntsman Path - Eraser",
 "64e7b99017ab941a6f7bf9d7": "Mall Cop",
 "64e7b9a4aac4cd0a726562cb": "Tickets, Please",
 "64e7b9bffd30422ed03dad38": "District Patrol",
 "68ee1c18b4e5bc9a68018cd7": "Special Order",
 "5edab736cc183c769d778bc2": "Colleagues",
 "5edaba7c0c502106f869bc02": "Tarkov-Style Diplomacy",
 "5b478eca86f7744642012254": "Vitamins",
 "64f5aac4b63b74469b6c14c2": "Glory to CPSU",
 "63a5cf262964a7488f5243ce": "Power of Persuasion",
 "639872fc93ae507d5858c3a6": "Gunsmith - Vector 9x19",
 "5b478ff486f7744d184ecbbf": "Supplements",
 "5edac34d0bb72a50635c2bfa": "A Difficult Choice",
 "64f5e20652fc01298e2c61e3": "Beyond the Red Meat",
 "64f6aafd67e11a7c6206e0d0": "The Secret Recipe",
 "5b47799d86f7746c5d6a5fd8": "Gunsmith - MPX",
 "5b4794cb86f774598100d5d4": "Metal Birds",
 "5d25e46e86f77409453bce7c": "First Aid",
 "64f5deac39e45b527a7c4232": "Job for a Patriot",
 "5ac244c486f77413e12cf945": "Gunsmith Master - Part 2",
 "65733403eefc2c312a759ddb": "Corporate Perks",
 "6573382e557ff128bf3da536": "The Secret to Productivity",
 "639872fe8871e1272b10ccf6": "Gunsmith Master - Part 1",
 "5b47891f86f7744d1b23c571": "Living High is Not a Crime",
 "6574e0dedc0d635f633a5805": "Getting Some Air",
 "5ae3280386f7742a41359364": "Gunsmith - AS VAL",
 "5ae449c386f7744bde357697": "Pathfinder",
 "5d25e45e86f77408251c4bfa": "The Huntsman Path - Liberation",
 "5c0d0f1886f77457b8210226": "From Hand to Hand",
 "5c10f94386f774227172c572": "Small Things, Big Help",
 "5ac242ab86f77412464f68b4": "Gunsmith Master - Part 3",
 "5c1141f386f77430ff393792": "Antique Enthusiast",
 "5b47749f86f7746c5d6a5fd4": "Gunsmith Master - Part 4",
 "669fa3a40c828825de06d6a1": "Easy-Breezy",
 "600302d73b897b11364cd161": "All This Filth...",
 "5b477b6f86f7747290681823": "Gunsmith Master - Part 5",
 "639135c3744e452011470807": "House Arrest",
 "675c1ff1a757ddd00404f0aa": "Unique Experience",
 "639873003693c63d86328f25": "Gunsmith Master - Part 6",
 "5b477f7686f7744d1b23c4d2": "Gunsmith Master - Part 7",
 "63987301e11ec11ff5504036": "Gunsmith Master - Part 8",
 "5b47825886f77468074618d3": "Gunsmith Master - Part 9",
 "64f83bb69878a0569d6ecfbe": "Gunsmith Master - Part 10",
 "64f83bcdde58fc437700d8fa": "Gunsmith Master - Part 11",
 "64f83bd983cfca080a362c82": "Gunsmith Master - Part 13",
 "60e729cf5698ee7b05057439": "Swift"
};

// Quests the wiki says are handed out by a different trader now.
const WIKI_TRADERS = {
 "6834233fecd5cf3a440d855b": "Fence"
};

if (typeof module !== 'undefined') module.exports = { WIKI_NAMES, WIKI_TRADERS };
