// GENERATED by _dev/build_wikireqs.js — do not hand-edit.
//
// Quest unlock requirements documented on the wiki that tarkov.dev has not
// published. EFT 1.1.0 moved much of the quest tree onto trader LOYALTY LEVEL
// and the data source is still catching up.
//
// ADDITIVE ONLY. Every row here is for a (quest, trader) pair tarkov.dev says
// nothing about — the generator drops anything that would override or duplicate
// it. This matters: 58 quests carry a minPlayerLevel the wiki page never
// mentions, so a wholesale import would silently delete real requirements.
//
// Source: escapefromtarkov.fandom.com, read 2026-08-04.
// Community-maintained and only as current as its editors; re-run to refresh.

const WIKI_TRADER_REQS = {
 "5d25e2cc86f77443e47ae019": [
  {
   "trader": "Jaeger",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "596b36c586f77450d6045ad2": [
  {
   "trader": "Skier",
   "kind": "loyalty",
   "value": 1
  }
 ],
 "5979eee086f774311955e614": [
  {
   "trader": "Skier",
   "kind": "loyalty",
   "value": 1
  }
 ],
 "5a27b75b86f7742e97191958": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "5a27b7a786f774579c3eb376": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 1
  }
 ],
 "5a27b7d686f77460d847e6a6": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "5a27b80086f774429a5d7e20": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "5a27b87686f77460de0252a8": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "6086c852c945025d41566124": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "6179b4d1bca27a099552e04e": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "6179aff8f57fb279792c60a1": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "669fa38fad7f1eac2607ed46": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "639135f286e646067c176a87": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "639282134ed9512be67647ed": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "639136f086e646067c176a8b": [
  {
   "trader": "Prapor",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "6578eb36e5020875d64645cd": [
  {
   "trader": "Jaeger",
   "kind": "loyalty",
   "value": 2
  }
 ],
 "5edac63b930f5454f51e128b": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "5b47926a86f7747ccc057c15": [
  {
   "trader": "Skier",
   "kind": "loyalty",
   "value": 1
  }
 ],
 "63a9b229813bba58a50c9ee5": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "63a9ae24009ffc6a551631a5": [
  {
   "trader": "Prapor",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "5c0be13186f7746f016734aa": [
  {
   "trader": "Mechanic",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "6179b5eabca27a099552e052": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "5c0d4c12d09282029f539173": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "5c0d4e61d09282029f53920e": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "639135534b15ca31f76bc317": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "60e71c9ad54b755a3b53eb66": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "60e71dc0a94be721b065bbfc": [
  {
   "trader": "Ragman",
   "kind": "loyalty",
   "value": 1
  }
 ],
 "5c51aac186f77432ea65c552": [
  {
   "trader": "Therapist",
   "kind": "loyalty",
   "value": 4
  },
  {
   "trader": "Prapor",
   "kind": "loyalty",
   "value": 4
  },
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  },
  {
   "trader": "Mechanic",
   "kind": "loyalty",
   "value": 4
  },
  {
   "trader": "Jaeger",
   "kind": "loyalty",
   "value": 4
  },
  {
   "trader": "Skier",
   "kind": "loyalty",
   "value": 4
  },
  {
   "trader": "Ragman",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "60e71dc67fcf9c556f325056": [
  {
   "trader": "Ragman",
   "kind": "loyalty",
   "value": 3
  }
 ],
 "60e71ccb5688f6424c7bfec4": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "60e71c11d54b755a3b53eb65": [
  {
   "trader": "Skier",
   "kind": "loyalty",
   "value": 4
  }
 ],
 "60e71ce009d7c801eb0c0ec6": [
  {
   "trader": "Peacekeeper",
   "kind": "loyalty",
   "value": 4
  }
 ]
};

// The Collector (Kappa) gate as rewritten in 1.1.0. Replaces the old
// "complete 257 side tasks" requirement, which tarkov.dev still publishes.
const KAPPA_GATE = {
 "taskId": "5c51aac186f77432ea65c552",
 "loyalty": [
  {
   "trader": "Therapist",
   "value": 4
  },
  {
   "trader": "Prapor",
   "value": 4
  },
  {
   "trader": "Peacekeeper",
   "value": 4
  },
  {
   "trader": "Mechanic",
   "value": 4
  },
  {
   "trader": "Jaeger",
   "value": 4
  },
  {
   "trader": "Skier",
   "value": 4
  },
  {
   "trader": "Ragman",
   "value": 4
  }
 ],
 "karma": 3,
 "quests": [
  {
   "names": [
    "Chemical - Part 4",
    "Big Customer",
    "Out of Curiosity"
   ],
   "ids": [
    "597a0f5686f774273b74f676",
    "597a171586f77405ba6887d3",
    "597a160786f77477531d39d2"
   ]
  },
  {
   "names": [
    "Shooter Born in Heaven"
   ],
   "ids": [
    "5c0bde0986f77479cf22c2f8"
   ]
  },
  {
   "names": [
    "The Tarkov Shooter - Part 4"
   ],
   "ids": [
    "5bc480a686f7741af0342e29"
   ]
  },
  {
   "names": [
    "Sew it Good - Part 2"
   ],
   "ids": [
    "5ae4495c86f7744e87761355"
   ]
  }
 ],
 "minPlayerLevel": 45
};

if (typeof module !== 'undefined') module.exports = { WIKI_TRADER_REQS, KAPPA_GATE };
